version: '3'

services:
  nba_mongo:
    image: mongo
    container_name: nba_mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db
    ports:
        - 27017:27017
  nba_scraping:
    build: .
    container_name: nba_scraping